config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "users/sign_out" => "users/sessions#destroy"
  end

  root "events#index"

  get "/user", to: "users#show"
  
  resources :events
  resources :event_attendences, only: [:create, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, foreign_key: :creator_id, class_name: 'User'

    has_many :event_attendences, foreign_key: :attended_event_id, dependent: :destroy
    has_many :attendees, through: :event_attendences, source: :event_attendee, dependent: :destroy

    validates :title, presence: true
    validates :description, presence: true
    validates :location, presence: true
    validates :date_time, presence: true

    scope :upcoming, -> { where("date_time >= ?", DateTime.now).order(:date) }
    scope :past, -> { where("date_time < ?", DateTime.now).order(:date) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @events = Event.all.includes(:creator, :attendees)
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.created_events.build(event_params)

        if @event.save
            redirect_to @event
        else  
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @event = Event.includes(:attendees).find(params[:id])

        event_attendee_ids = @event.attendees.map(&:id)

        if current_user 
            @current_user_attends = event_attendee_ids.include?(current_user.id) ? true : false
        else
            @current_user_attends = nil
        end
    end

    def edit
        @event = Event.find(params[:id])
    end
    
    def update
        @event = Event.find(params[:id])
    
        if @event.update(event_params)
          redirect_to @event
        else
          render :new, status: :unprocessable_entity
        end
    end
    
    def destroy
        @event = Event.find(params[:id])
    
        @event.destroy
    
        redirect_to root_path
    end

    private

    def event_params
        params.require(:event).permit(:title, :description, :location, :date_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
<div class="form">
  <div class="input">
    <%= form.label :title, "Event" %><br>
    <%= form.text_field :title %>
    <% @event.errors.full_messages_for(:title).each do |message| %>
      <div class="field_with_errors"><span><%= message %></span></div>
    <% end %>
  </div><br>

  <div class="input">
    <%= form.label :description, "Event Description" %><br>
    <%= form.text_area :description, size: "30x5" %>
    <% @event.errors.full_messages_for(:description).each do |message| %>
      <div class="field_with_errors"><span><%= message %></span></div>
    <% end %>
  </div><br>

  <div class="input">
    <%= form.label :location, "Place" %><br>
    <%= form.text_field :location %>
    <% @event.errors.full_messages_for(:location).each do |message| %>
      <div class="field_with_errors"><span><%= message %></span></div>
    <% end %>
  </div><br>

  <div class="date-local">
    <%= form.label :date_time, "Date & Time" %><br>
    <%= form.datetime_local_field :date_time%>
    <% @event.errors.full_messages_for(:date_time).each do |message| %>
      <div class="field_with_errors"><span><%= message %></span></div>
    <% end %>
  </div><br>

  <div class="button">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h1>Events</h1>

<div class="future-events">
  <h4>Upcoming Events:</h4>
  <% if Event.upcoming.any? %>
    <% Event.upcoming.each do |event| %>
      <ul>
        <li><%= event.title%>: <%= link_to "See details", event_path(event) %></li>
      </ul>
    <% end %>
  <% else %>
    <p>No upcoming events found</p>
  <% end %>
</div>

<div class="past-events">
  <h4>Past Events:</h4>
  <% if Event.past.any? %>
    <% Event.past.each do |event| %>
      <ul>
        <li><%= event.title %>: <%= link_to "See details", event_path(event) %></li>
      </ul>
    <% end %>
  <% else %>
    <p>No events have happened yet</p>
  <% end %>
</div><br>

<div class="links">
  <% if user_signed_in? %>
    <p>Create a <%= link_to "new event", new_event_path %></p>
    <p>View <%= link_to "your page", user_path %></p>
    <p>Sign out <%= link_to "here", destroy_user_session_path, method: :delete %></p>
  <% else %>
    <p>Sign in <%= link_to "here", user_session_path %></p>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<p>Event Creator: <%= @event.creator.email.split("@")[0] %></p>
<p>Description: <%= @event.description %></p>
<p>Location: <%= @event.location %></p>
<p>Date and Time: <%= @event.date_time.strftime("%m/%d/%Y: %l:%M %p") %></p><br>

<% if current_user == @event.creator %>
  <% if @event.date_time >= DateTime.now %>
    <%= link_to "Edit Event", edit_event_path(@event) %><br>
    <%= link_to "Delete Event", event_path(@event), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
      } %><br><br>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <% if @event.date_time >= DateTime.now %>
    <% if @current_user_attends %>
      <%= link_to "Do not attend", event_attendence_path(event_attendence: {event_attendee_id: current_user.id, attended_event_id: @event.id}), data: {turbo_method: "delete"} %>
    <% else %>
      <%= link_to "Attend", event_attendences_path(event_attendence: {event_attendee_id: current_user.id, attended_event_id: @event.id}), data: {turbo_method: "post"}%>
    <% end %>
  <% end %>
<% else %>
  <% if @event.date_time >= DateTime.now %>
    <p>Log in to be able to attend.</p>
  <% else %>
    <p>This event has already occurred.</p>
  <% end %>
<% end %>

<% if @event.date_time >= DateTime.now %>
  <p>Attendees (<%= @event.attendees.length %>):</p>
  <ul>
    <% if user_signed_in? %>
      <% @event.attendees.each do |attendee| %>
        <li><%= attendee.email.split("@")[0] %></li>
      <% end %>
    <% else %>
      <li>Log in too see who attends.</li>
    <% end %>
  </ul>
<% else %>
  <% if @current_user_attends %>
    <% if @event.attendees.length > 2 %>
      <p>You and <%= @event.attendees.length - 1 %> others attended this event</p><br>
    <% elsif @event.attendees.length > 1 %>
      <p>You and <%= @event.attendees.length - 1 %> other attended this event</p><br>
    <% else %>
      <p>Only you attended this event</p><br>
    <% end %>
  <% elsif @event.attendees.length > 1 %>
    <p><%= @event.attendees.length %> people attended this event</p><br>
  <% elsif @event.attendees.length > 0 %>
    <p><%= @event.attendees.length %> person attended this event</p><br>
  <% else %>
    <p>No one attended this event</p><br>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <p>Go back to <%= link_to "your page", user_path %></p>
<% end %>
<p>Go back to <%= link_to "home page", root_path %></p>